# Generated by Django 5.1.4 on 2025-01-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm_app.lead')),
            ],
        ),
    ]
