# Generated by Django 5.1.4 on 2025-01-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
